name: Rick And Morty CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Pipeline iniciada
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"🚀 Pipeline iniciada\n👤 Autor: ${{ github.actor }}\n🌿 Branch: ${{ github.ref_name }}\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: 📥 Checkout projeto
        uses: actions/checkout@v4

      - name: 📢 Aviso checkout
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"📥 Código baixado com sucesso"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: ⚙️ Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 📢 Aviso node
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"⚙️ Node configurado"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: 📦 Instalando dependências
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"📦 Instalando dependências..."}' \
          ${{ secrets.DISCORD_WEBHOOK }}

          npm ci

      - name: 🏗️ Build Angular
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"🏗️ Executando build Angular..."}' \
          ${{ secrets.DISCORD_WEBHOOK }}

          npm run build

      - name: ✅ Build sucesso
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"✅ Build finalizada com sucesso\n📦 Repositório: ${{ github.repository }}\n🌿 Branch: ${{ github.ref_name }}\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: ❌ Capturar erro
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"content\": \"❌ A pipeline falhou!\n📦 Repositório: ${{ github.repository }}\n🌿 Branch: ${{ github.ref_name }}\n🔎 Verifique os logs no GitHub Actions\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
