name: Rick And Morty CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Pipeline iniciada
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: info
          title: "🚀 Pipeline iniciada"
          description: "Iniciando processo CI/CD"

      - name: 📥 Checkout projeto
        uses: actions/checkout@v4

      - name: 📢 Checkout concluído
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: info
          title: "📥 Checkout concluído"

      - name: ⚙️ Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: 📢 Node configurado
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: info
          title: "⚙️ Node configurado"

      - name: 📦 Instalar dependências
        run: npm install

      - name: 📢 Dependências instaladas
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: info
          title: "📦 Dependências instaladas"

      - name: 🏗️ Build Angular
        run: npm run build

      - name: 📢 Build Angular concluído
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: info
          title: "🏗️ Build Angular concluído"

      - name: ✅ Pipeline sucesso
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: success
          title: "✅ Pipeline finalizada"
          description: "Build executada com sucesso"

      - name: ❌ Pipeline falhou
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          title: "❌ Pipeline falhou"
          description: "Alguma etapa da build apresentou erro"
