name: Rick And Morty CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Aviso início
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"🚀 Build iniciada"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Checkout projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Build Angular
        run: npm run build

      - name: ✅ Sucesso
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"✅ Build finalizada com sucesso"}' \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: ❌ Falha
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content":"❌ Build falhou"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
